events { worker_connections 1024; }

http {
  upstream analyse   { server analyse:8001; }
  upstream ocr       { server ocr:8002; }
  upstream rag       { server rag:8003; }
  upstream translate { server translate:8004; }

  server {
    listen 80;

    # increase timeout for OCR (can take 40s)
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;

    location /analyse    { proxy_pass http://analyse; }
    location /explain    { proxy_pass http://analyse; }
    location /api        { proxy_pass http://analyse; }
    location /ocr        { proxy_pass http://ocr; }
    location /rag        { proxy_pass http://rag; }
    location /translate  { proxy_pass http://translate; }

    location /health {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}
